name: Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yml

  check-coverage:
    name: Python Code Coverage
    runs-on: ubuntu-latest
    needs: lint-test
    permissions:
      contents: read
      pull-requests: write
    env:
      # TODO: 5% of coverage is pretty low.
      # We should increase this value after Friday.
      COVERAGE_THRESHOLDS: '0 50'
    steps:
    - name: Download Coverage Report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: .

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        badge: true
        output: 'both'
        format: 'markdown'
        hide_complexity: true
        hide_branch_rate: false
        filename: 'coverage.xml'
        thresholds: ${{ env.COVERAGE_THRESHOLDS }}

    - name: Cat coverage.md file
      run: cat code-coverage-results.md

    - name: Comment on Pull Request
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Code Coverage Threshold Check
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        fail_below_min: true
        filename: 'coverage.xml'
        hide_branch_rate: false
        thresholds: ${{ env.COVERAGE_THRESHOLDS }}
